{
 "title": "Metricbeat, Elastic, System metricset",
 "description": "Metricbeat, Elastic, System metricset. Based on System metrics by erhwenkuo.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"beat.hostname\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:cpu  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "aasd",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU cores utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.core.id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.core.user.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:core  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load 5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "aasd",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load 15",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.15",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "memory",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.used.pct",
       "id": "1",
       "inlineScript": "Math.round(_value*10000)/10000.0",
       "meta": {},
       "settings": {
        "script": {
         "inline": "Math.round(_value*10000)/10000.0"
        }
       },
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:memory  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:system AND metricset.name:filesystem  AND beat.hostname:$Host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In / Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "network in",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "beat.hostname:$Host AND !system.network.name:\"IBM USB Remote NDIS Network Device\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "network out",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "beat.hostname:$Host AND !system.network.name:\"IBM USB Remote NDIS Network Device\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}